config/routes.rb
Cerohisteria::Application.routes.draw do
  resources :categories

  resources :images
  match '/images/new/(:id)' => 'images#new', :as => 'image_new'
  
  resources :imgcomments

  resources :authors
  
  resources :comments do
    resources :comments
  end

  resources :posts do
    resources :comments
  end
 
  
  root :to => "posts#index"
  
  match '/:slug/:id/', :controller => 'posts', :action => 'show', :as => "viewpost"
  match '/recomendados/', :controller => 'posts', :action => 'recomendados', :as => "recomendados"
  match '/categorias', :controller => 'categories', :action => 'categorias'
  match '/posts/:slug/:id', :controller => 'posts', :action => 'categoria', :as => "categoria"
  match '/recomendados', :controller => 'posts', :action => 'recomendados', :as => "recomendados"
  
  resources :sessions, :posts
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :avatar, :description, :nickname
  has_many :posts
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :authorize, :except => [:index, :show]
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.text_area :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Nickname</th>
    <th>Description</th>
    <th>Avatar</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.nickname %></td>
    <td><%= author.description %></td>
    <td><img alt="avatar" src="data:image;base64,<%= author.avatar %>" width="150" /></td>
    <td><%= link_to 'Show', author %></td>
	<% if admin? %>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, confirm: 'Are you sure?', method: :delete %></td>
	<% end %>
  </tr>
<% end %>
</table>

<br />
<% if admin? %>
<%= link_to 'New Author', new_author_path %>
<% end %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nickname:</b>
  <%= @author.nickname %>
</p>

<p>
  <b>Description:</b>
  <%= @author.description %>
</p>

<p>
<img alt="avatar" src="data:image/jpg;base64,<%= @author.avatar %>" width="150" />
</p>

<% if admin? %>
<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>
<% end %>