config/routes.rb
Cerohisteria::Application.routes.draw do
  resources :categories

  resources :images
  match '/images/new/(:id)' => 'images#new', :as => 'image_new'
  
  resources :imgcomments

  resources :authors
  
  resources :comments do
    resources :comments
  end

  resources :posts do
    resources :comments
  end
 
  
  root :to => "posts#index"
  
  match '/:slug/:id/', :controller => 'posts', :action => 'show', :as => "viewpost"
  match '/recomendados/', :controller => 'posts', :action => 'recomendados', :as => "recomendados"
  match '/categorias', :controller => 'categories', :action => 'categorias'
  match '/posts/:slug/:id', :controller => 'posts', :action => 'categoria', :as => "categoria"
  match '/recomendados', :controller => 'posts', :action => 'recomendados', :as => "recomendados"
  
  resources :sessions, :posts
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :author_id, :body, :category_id, :keywords, :mainimg, :slug, :title, :recomended
  belongs_to :author
  belongs_to :category
  validates :category_id, :presence => true
  has_many :images
  has_many :comments, :as => :commentable
  #accepts_nested_attributes_for :postcomments
  
  before_save :slug_from_title
  private
  
  def slug_from_title
    titleorig =self.title
    titleorig= titleorig.downcase
    titleorig.gsub! /['`]/,""
    titleorig.gsub! /\s*[^A-Za-z0-9\.\-]\s*/, '-'
    titleorig.gsub! /_+/,"-"
    titleorig.gsub! /\A[_\.]+|[_\.]+\z/,""
      
    self.slug = titleorig
  end
    
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authorize, :except => [:index, :show, :recomendados,:aside_recomendados, :categoria]
  helper_method :aside_recomendados
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end
  
  def recomendados
    @recomendados = Post.where(:recomended =>true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recomendados }
    end
  end
  
  
  def aside_recomendados
    @aside_recomendados = Post.where(:recomended =>true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @aside_recomendados }
    end
  end
  
  def categoria
    @posts = Post.where(:category_id => params[:id])
    @meta_title = params[:slug]
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end
  
  def mas_recientes
    Posts.order(created_at DESC).limit(3)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    
    @meta_title = @post.title
    @meta_keywords = @post.keywords
    @meta_description = @post.body
    
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @Categories = Category.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created. ' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/posts/_aside_recomendados.html.erb
<% @aside_recomendados.each do |post| %>
	<li><%= link_to post.title, viewpost_path(post.slug,post.id) %></li>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
  <%= select("post", "category_id", Category.all.collect {|p| [ p.name, p.id ] }) %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br />
	<%= select("post", "author_id", Author.all.collect {|p| [ p.nickname, p.id ] }) %>
  </div>
  <div class="field">
    <%= f.label :mainimg %><br />
    <%= f.number_field :mainimg %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
<div class="field">
    <%= f.label :recomended %><br />
    <%= f.check_box :recomended %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/categoria.html.erb
<% @posts.each do |post| %>
<article>
	<div class="full"><h2><%= link_to post.title, viewpost_path(post.slug,post.id) %></h2></div>
	<% if post.mainimg != nil%>
	<div class="one_3">
	<% else %>
	<div class="col_three_4">
	<% end %>	
		<% if post.mainimg != nil%>
	
		<% bringmainimg(post.mainimg) %>
		<div class="thumbindex">
		<img src="data:image;base64,<%= @image_file %>" title="<%= @image_title %>" class="auto-image"/>
		</div>
		<% end %>
		<% if admin? %>
		<p>
			
		<%= link_to 'Edit', edit_post_path(post), :class => 'adminlink'%>
		<%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete, :class => 'adminlink'%>
<%= link_to '+ Imagen', image_new_path(post.id), :class => 'adminlink' %>			
		
		</p>
		<% end %>
		
		
		<% if post.mainimg != nil%>
		</div>
		<div class="one_3">
		<% end %>
		<p>Autor:<%= post.author.nickname %> </p>
	
		<p><%= truncate(post.body, :length => 400) %></p>

		
	</div>
</article>
<% end %>
<% if admin? %>
<%= link_to 'New Post', new_post_path, :class => 'adminlink' %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<article>
	<div class="full"><h2><%= link_to post.title, viewpost_path(post.slug,post.id) %></h2></div>
	<% if post.mainimg != nil%>
	<div class="one_3">
	<% else %>
	<div class="col_three_4">
	<% end %>	
		<% if post.mainimg != nil%>
	
		<% bringmainimg(post.mainimg) %>
		<div class="thumbindex">
		<img src="data:image;base64,<%= @image_file %>" title="<%= @image_title %>" class="auto-image"/>
		</div>
		<% end %>
		<% if admin? %>
		<p>
			
		<%= link_to 'Edit', edit_post_path(post), :class => 'adminlink'%>
		<%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete, :class => 'adminlink'%>
<%= link_to '+ Imagen', image_new_path(post.id), :class => 'adminlink' %>			
		
		</p>
		<% end %>
		
		
		<% if post.mainimg != nil%>
		</div>
		<div class="one_3">
		<% end %>
		<p>Autor: <%= post.author.nickname %>  <span> <%= link_to post.category.name, categoria_path(post.category.slug,post.category.id) %></span></p>
		
		<p><%= truncate(post.body, :length => 400) %></p>

		
	</div>
</article>
<% end %>
<% if admin? %>
<%= link_to 'New Post', new_post_path, :class => 'adminlink' %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/recomendados.html.erb
<h3>Mas Recomendados</h3>

<% @recomendados.each do |post| %>
<article>
	<div class="full"><h2><%= link_to post.title, viewpost_path(post.slug,post.id) %></h2></div>
	<% if post.mainimg != nil%>
	<div class="one_3">
	<% else %>
	<div class="col_three_4">
	<% end %>	
		<% if post.mainimg != nil%>
	
		<% bringmainimg(post.mainimg) %>
		<div class="thumbindex">
		<img src="data:image;base64,<%= @image_file %>" title="<%= @image_title %>" class="auto-image"/>
		</div>
		<% end %>
		<% if admin? %>
		<p>
			
		<%= link_to 'Edit', edit_post_path(post), :class => 'adminlink'%>
		<%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete, :class => 'adminlink'%>
<%= link_to '+ Imagen', image_new_path(post.id), :class => 'adminlink' %>			
		
		</p>
		<% end %>
		
		
		<% if post.mainimg != nil%>
		</div>
		<div class="one_3">
		<% end %>
		<p>Autor:<%= post.author.nickname %> </p>
		<p><%= truncate(post.body, :length => 400) %></p>

		
	</div>
</article>
<% end %>
<% if admin? %>
<%= link_to 'New Post', new_post_path, :class => 'adminlink' %>
<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<article>
	<h1><%= @post.title %></h1>
	<p>
	  <span class="categoryname"><%= link_to @post.category.name, categoria_path(@post.category.slug,@post.category.id) %></span>
	  <span class="timepost"><%= distance_of_time_in_words(Time.now, @post.created_at).capitalize %></span>
		
	</p>
	<p><%= @post.body %></p>
	<!-- images -->

	<% bringimages(@post.id) %>

	<% @images.each do |image|%>
	<img src="data:image;base64,<%= image.filename %>" title="<%= image.title %>" class="auto-image"/>
	<% end %>
	<p>
	  <%= @post.keywords %>
	</p>

	
	<div id="author">
	<div class="inside">
	<img alt="avatar" title="<%= @post.author.nickname %>" src="data:image/jpg;base64,<%= @post.author.avatar %>" width="120" />
	<div class="authorinfo">
		<h3>Autor: <%= @post.author.nickname %></h3>
		<p><%= @post.author.description %></p>
	</div>

	</div>
	</div>
	<% if admin? %>
	<%= link_to 'Edit', edit_post_path(@post) %> |
	<%= link_to 'Back', posts_path %>
	<% end %>
</article>
<div id="comments">
<h3>Comentarios</h3>

<p><%= link_to 'Comentar', new_post_comment_path(@post) %></p>


<%= render :partial => 'comments/comment', :collection => @post.comments %>



</div>